export const projects = [
  {
    id: 1,
    title: "ClassMate",
    description:
      "Full-stack campus management platform with attendance tracking (ClassPulse), P2P skill exchange (SkillSwap), internship aggregator, and carpooling.",
    category: "fullstack",
    technologies: ["React 18", "Node.js", "PostgreSQL", "Sequelize", "Tailwind CSS"],
    year: "2025",
    image: "/Project/ProjectImages/ClassMate.png",
    github: "https://github.com/keshavagr273/ClassMate",
    live: "https://class-matefrontend.vercel.app/",
  },
  {
    id: 2,
    title: "HydraCache",
    description:
      "A decentralized, fault-tolerant in-memory distributed key-value store with 64-bit Murmur3 consistent hashing, SWIM gossip, and HLC timestamps.",
    category: "distributed",
    technologies: ["TypeScript", "Node.js", "SWIM Gossip", "Docker", "HLC Clocks"],
    year: "2026",
    image: "/Project/ProjectImages/hydracache.png",
    github: "https://github.com/keshavagr273/HydraCache",
    live: "https://github.com/keshavagr273/HydraCache",
  },
  {
    id: 3,
    title: "DocSaarthi",
    description:
      "AI-powered multilingual document intelligence platform for Hindi, Devanagari, and English with PaddleOCR v4, hybrid search (pgvector + pg_trgm), and conversational RAG.",
    category: "ai-ml",
    technologies: ["Next.js 15", "NestJS", "PaddleOCR", "pgvector", "PostgreSQL", "RAG"],
    year: "2026",
    image: "/Project/ProjectImages/DocSaarthi.png",
    github: "https://github.com/keshavagr273/DocSaarthi",
    live: "https://docsaarthi.vercel.app/",
  },
  {
    id: 4,
    title: "ChatSphere",
    description:
      "Full-stack communication app with direct & group messaging via Socket.IO, WebRTC video/voice calls, typing indicators, and presence.",
    category: "fullstack",
    technologies: ["React", "Node.js", "Socket.IO", "WebRTC", "MongoDB", "Zustand"],
    year: "2026",
    image: "/Project/ProjectImages/chat.png",
    github: "https://github.com/keshavagr273/Chat-App",
    live: "https://chat-app-one-xi-68.vercel.app/",
  },
  {
    id: 5,
    title: "Equity Nest",
    description:
      "Real-time stock trading SaaS delivering live Upstox binary WebSocket feeds, TradingView charts, and in-memory NSE symbol fuzzy search.",
    category: "fullstack",
    technologies: ["Next.js", "Express.js", "Socket.io", "Protobuf", "MongoDB"],
    year: "2025",
    image: "/Project/ProjectImages/equity.png",
    github: "https://github.com/keshavagr273/Equity-Nest.git",
    live: "https://equity-nest-mjil.vercel.app/",
  },
  {
    id: 6,
    title: "Luminary AI",
    description:
      "AI-powered academic planning platform for university discovery, admissions guidance, document processing, and ROI calculators.",
    category: "ai-ml",
    technologies: ["React", "Node.js", "AI/ML", "Express", "Tailwind CSS"],
    year: "2026",
    image: "/Project/ProjectImages/Luminary.png",
    github: "https://github.com/keshavagr273/Luminary-AI",
    live: "https://luminary-ai-nine.vercel.app/",
  },
  {
    id: 7,
    title: "FreshFinds",
    description:
      "Community marketplace connecting local vendors with nearby customers to resell fresh surplus food at discounted prices.",
    category: "fullstack",
    technologies: ["React", "Node.js", "MongoDB", "JavaScript", "Tailwind CSS"],
    year: "2025",
    image: "/Project/ProjectImages/FreshFinds.png",
    github: "https://github.com/keshavagr273/FreshFinds",
    live: "https://fresh-finds-beige.vercel.app/",
  },
  {
    id: 8,
    title: "Agricare",
    description:
      "Full-stack agricultural platform with digitalized inventory management, dynamic marketplace, and multi-language support (i18n).",
    category: "fullstack",
    technologies: ["React", "Node.js", "Express", "Redux", "Tailwind CSS", "i18n"],
    year: "2025",
    image: "/Project/ProjectImages/Agricare.png",
    github: "https://github.com/keshavagr273/AgriCare",
    live: "https://agri-care-sage.vercel.app/",
  },
  {
    id: 9,
    title: "Heart Disease Predictor",
    description:
      "Web app predicting heart disease risk using user health data and deep neural network model trained on BRFSS 2015 dataset.",
    category: "ai-ml",
    technologies: ["React", "Next.js", "TensorFlow", "Keras", "Python"],
    year: "2025",
    image: "/Project/ProjectImages/heart1.png",
    github: "https://github.com/keshavagr273/heart-disease-app",
    live: "https://huggingface.co/spaces/keshav273/heart-pred-app",
  },
  {
    id: 10,
    title: "Faculty Project Tracker",
    description:
      "Admin dashboard for supervising faculty to track student project milestones, inactive group alerts, and CSV data export.",
    category: "fullstack",
    technologies: ["React", "Node.js", "MongoDB", "JWT", "Express"],
    year: "2025",
    image: "/Project/ProjectImages/project.png",
    github: "https://github.com/keshavagr273/MinorProject-Tracker",
    live: "https://minor-project-tracker.vercel.app/",
  },
];